---
version: "3.0"

services:
  ############################################
  #
  # Prod and Dev Services
  #
  ############################################
  api:
    build:
      context: .
      args:
        NODE_ENV: production
    image: ffl-api
    container_name: api
    entrypoint: ["npm", "run", "start:prod"]
    depends_on:
      - redis
    networks:
      - bubble
      - earth

  api-dev:
    build:
      context: .
      args:
        NODE_ENV: development
    image: ffl-api-dev
    entrypoint: ["npm", "run", "start:dev"]
    depends_on:
      - redis
    networks:
      - bubble
      - earth
    volumes:
      - .:/app

  ############################################
  #
  # Dev Tools
  #
  ############################################
  dev-tool: &dev-tool
    build:
      context: .
      args:
        NODE_ENV: development
    image: ffl-dev-tool
    volumes:
      - .:/app:rw
      - ./package.json:/etc/ffl-api/package.json:rw

  prettify:
    <<: *dev-tool
    entrypoint: ["npm", "run", "prettify"]

  lock-packages:
    <<: *dev-tool
    entrypoint: >
      sh -c "rm -rf /etc/ffl-api/node_modules /etc/ffl-api/package-lock.json && npm install --prefix /etc/ffl-api && cp /etc/ffl-api/package-lock.json /app/"

  ############################################
  #
  # Database & Tools
  #
  ############################################
  redis:
    image: redis:7.0
    container_name: redis
    restart: on-failure
    command: ["redis-server", "--port", "6379"]
    networks:
      - bubble

  redis-cli:
    image: redis:7.0
    entrypoint: ["redis-cli", "-h", "redis", "-p", "6379"]
    networks:
      - bubble
    depends_on:
      - redis

networks:
  bubble:
    internal: True
  earth:
    external: True
